import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { AnyNode, AnyNodeId } from '@pascal-app/core/schema'
import { z } from 'zod'
import type { Patch as BridgePatch } from '../bridge/scene-bridge'
import type { SceneOperations } from '../operations'
import { DESTRUCTIVE_TOOL_ANNOTATIONS } from './annotations'
import { ErrorCode, throwMcpError } from './errors'
import { liveSyncOutput, persistencePayload, publishLiveSceneSnapshot } from './live-sync'
import { PatchSchema } from './schemas'

export const applyPatchInput = {
  patches: z.array(PatchSchema),
}

export const applyPatchOutput = {
  appliedOps: z.number(),
  deletedIds: z.array(z.string()),
  createdIds: z.array(z.string()),
  ...liveSyncOutput,
}

export function registerApplyPatch(server: McpServer, bridge: SceneOperations): void {
  server.registerTool(
    'apply_patch',
    {
      title: 'Apply patch',
      description:
        'Apply a batch of create/update/delete operations atomically. All patches are validated before any are applied; the entire batch forms a single undo step. Batch-first is the default: prefer one apply_patch call containing all create/update/delete ops for a build step, in stable order so later ops can reference ids created by earlier ops. A single call is atomic (all or nothing) and pays the snapshot and save cost once; do not loop one-op calls. Nodes generated by a facade are refused: change a facade with apply_facade.',
      inputSchema: applyPatchInput,
      outputSchema: applyPatchOutput,
      annotations: DESTRUCTIVE_TOOL_ANNOTATIONS,
    },
    async ({ patches }) => {
      const refusal = facadeOwnedPatch(patches, bridge.getNodes() as Record<string, AnyNode>)
      if (refusal) throwMcpError(ErrorCode.InvalidParams, refusal)
      const bridgePatches: BridgePatch[] = patches.map((p) => {
        if (p.op === 'create') {
          return {
            op: 'create',
            node: p.node as unknown as AnyNode,
            ...(p.parentId !== undefined ? { parentId: p.parentId as AnyNodeId } : {}),
          }
        }
        if (p.op === 'update') {
          return {
            op: 'update',
            id: p.id as AnyNodeId,
            data: p.data as Partial<AnyNode>,
          }
        }
        return {
          op: 'delete',
          id: p.id as AnyNodeId,
          ...(p.cascade !== undefined ? { cascade: p.cascade } : {}),
        }
      })

      try {
        const result = bridge.applyPatch(bridgePatches)
        const persistence = await publishLiveSceneSnapshot(bridge, 'apply_patch')
        const payload = {
          appliedOps: result.appliedOps,
          deletedIds: result.deletedIds as unknown as string[],
          createdIds: result.createdIds as unknown as string[],
          ...persistencePayload(persistence),
        }
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(payload) }],
          structuredContent: payload,
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        throwMcpError(ErrorCode.InvalidParams, msg)
      }
    },
  )
}

/**
 * A facade owns what it generates and re-solves it on the next fill, so a
 * patch editing or forging one of those nodes would be silently undone.
 */
function facadeOwnedPatch(
  patches: readonly z.infer<typeof PatchSchema>[],
  nodes: Record<string, AnyNode>,
): string | null {
  for (const [index, patch] of patches.entries()) {
    const owner =
      patch.op === 'create'
        ? (patch.node as { metadata?: Record<string, unknown> }).metadata?.facadeOwner
        : nodes[patch.id]?.metadata?.facadeOwner
    if (owner)
      return `patches[${index}] targets a node generated by the facade on wall ${String(owner)}. Change the facade with apply_facade instead.`
  }
  return null
}
